name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor
        key: v1-dependencies-${{ hashFiles('composer.lock') }}
        restore-keys: |
          v1-dependencies-${{ hashFiles('composer.lock') }}
    - uses: php-actions/composer@v1 # or alternative dependency management
    - name: Run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix ./ --diff --dry-run
    - uses: php-actions/phpunit@v1
      with:
        config: phpunit.xml
