name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.3'
        coverage: xdebug
        extensions: xdebug
    - name: Cache Packages
      uses: actions/cache@v1
      with:
        path: vendor
        key: v2-dependencies-${{ hashFiles('composer.lock') }}
        restore-keys: |
          v2-dependencies-${{ hashFiles('composer.lock') }}
    - uses: php-actions/composer@v1 # or alternative dependency management
    - name: Run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix ./ --diff --dry-run
    - name: Run phpunit
      run: ./vendor/bin/phpunit
    - name: Upload Coverage report
      run: |
        php -i
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
