name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor
        key: v1-dependencies-${{ hashFiles('composer.lock') }}
        restore-keys: |
          v1-dependencies-${{ hashFiles('composer.lock') }}
    - uses: php-actions/composer@v1 # or alternative dependency management
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff --dry-run
    - uses: php-actions/phpunit@v1
